### ISSUE TITLE
Regarding dataset used

### ISSUE THREAD

**Issue by Baibhav-nag** [SwethaRavi30/music-player#1]
Please tell me what dataset u have used

**Comment by SwethaRavi30** [comment]
> Please tell me what dataset u have used

GTZAN dataset

**Comment by Baibhav-nag** [comment]
Thank you very much

**Comment by Baibhav-nag** [comment]
Just one query...from where are u getting the emotion tags for training...the dataset only has audio files with genre tags...cannot understand this part of your code...please clarify.

![2021-03-24_LI](https://user-images.githubusercontent.com/74949243/112347516-ee1d4c00-8cec-11eb-96b3-65208b87217e.jpg)

**Comment by SwethaRavi30** [comment]
> Just one query...from where are u getting the emotion tags for training...the dataset only has audio files with genre tags...cannot understand this part of your code...please clarify.
> 
> ![2021-03-24_LI](https://user-images.githubusercontent.com/74949243/112347516-ee1d4c00-8cec-11eb-96b3-65208b87217e.jpg)

I have used ravdess dataset for emotion recognition.

**Comment by SwethaRavi30** [comment]
Then I just combined these two separate projects.

**Comment by Baibhav-nag** [comment]
Ok thank you very much

**Comment by Baibhav-nag** [comment]
When I try to implement your code it gives the following error...cannot understand please help

![2021-03-25](https://user-images.githubusercontent.com/74949243/112489861-dbfee480-8da4-11eb-9505-72d284a3bb11.png)

**Comment by Baibhav-nag** [comment]
Thank you very much for all your help and assistance. Really helped me a lot.
